### ISSUE TITLE
Error: The bundle does not match the connected device

### ISSUE THREAD

**Issue by efkan** [Androxyde/Flashtool#126]
When trying to flash a downloaded `*.ftf` file I get the error of `The bundle does not match the connected device` constantly.

Although I chose the correct model as Xperia Z `C6603` I couldn't figure it out why it ends up with this error. Also I tried a couple of different version from `Xperifirm`..

So, I wonder that is there any possibility to overcome this issue for `C6603`?

**Comment by diegocrzt** [comment]
did you solve the problem ?

**Comment by darkfader** [comment]
I have the same issue. I can't even use Flashtool nor the official Sony tool anymore!
