### ISSUE TITLE
C2005. ERROR - The bundle does not match the connected device

### ISSUE THREAD

**Issue by SkyNetCoder** [Androxyde/Flashtool#145]
Flashtool version:  0.9.28.0.
Device: Xperia M Dual (C2005).
When trying to flash *.ftf file I get the error of **The bundle does not match the connected device**.
C2005 was recognized as F5121. Why?

Log:
`28/004/2020 10:04:19 - INFO  - Flashtool 0.9.28.0`
`28/004/2020 10:04:19 - INFO  - Searching for a web proxy`
`28/004/2020 10:04:20 - INFO  - No proxy found, using direct connection`
`28/004/2020 10:04:20 - INFO  - Syncing devices from github`
`28/004/2020 10:04:20 - INFO  - Opening devices repository.`
`28/004/2020 10:04:20 - INFO  - Scanning devices folder for changes.`
`28/004/2020 10:04:30 - INFO  - Pulling changes from github.`
`28/004/2020 10:04:31 - INFO  - Devices sync finished.`
`28/004/2020 10:04:33 - INFO  - Loading devices database`
`28/004/2020 10:04:33 - INFO  - Loaded 127 devices`
`28/004/2020 10:04:33 - INFO  - Starting phone detection`
`28/004/2020 10:04:35 - INFO  - Device disconnected`
`28/004/2020 10:04:46 - INFO  - Flash canceled`
`28/006/2020 10:06:02 - INFO  - Selected Bundle for Sony Xperia M Dual(C2005). FW release : 15.5.A.1.5. Customization : GenericFirmware`
`28/006/2020 10:06:02 - INFO  - Preparing files for flashing`
`28/006/2020 10:06:34 - INFO  - Please connect your device into flashmode.`
`28/006/2020 10:06:46 - INFO  - Using Gordon gate drivers version 3.2.0.0`
`28/006/2020 10:06:46 - INFO  - Opening device for R/W`
`28/006/2020 10:06:47 - INFO  - Device ready for R/W.`
`28/006/2020 10:06:47 - INFO  - Reading device information`
`28/006/2020 10:06:47 - INFO  - Phone ready for flashmode operations.`
`28/006/2020 10:06:47 - INFO  - Opening TA partition 2`
`28/006/2020 10:06:47 - INFO  - Current device : F5121 - YT910UXUZ3 - Unknown: May  9 2014/12:58:25 - Unknown: May  9 2014/12:58:25 - GENERIC_34.1.A.1.198`
`28/006/2020 10:06:47 - INFO  - Closing TA partition`
`28/006/2020 10:06:47 - ERROR - The bundle does not match the connected device`
`28/006/2020 10:06:47 - INFO  - Ending flash session`
`28/006/2020 10:06:48 - INFO  - Device disconnected`
`28/006/2020 10:06:55 - INFO  - Device connected in flash mode`
`28/007/2020 10:07:53 - INFO  - Device disconnected`
`28/008/2020 10:08:14 - INFO  - Device connected with USB debugging off`
`28/008/2020 10:08:14 - INFO  - For 2011 devices line, be sure you are not in MTP mode`
`28/012/2020 10:12:01 - INFO  - Device disconnected`

But if I use flashtool version 0.9.18.6 it's all OK.

**Comment by diegocrzt** [comment]
Same issue in arch linux 65 bit, will try with an older version

**Comment by diegocrzt** [comment]
In my case the 0.9.18.6 version worked also.

**Comment by SkyNetCoder** [comment]
In my case it was my fault: i flashed Xperia Overlay ROM witch is based on F5121 ROM. That is the reason why phone was recognized as F5121.

**Comment by diegocrzt** [comment]
@SkyNetCoder, I am pretty sure I didn't mix the the ROM, actually, I used this version 0.9.18.6 (and previous versions) with my Xperia V and it worked flawlessly, so I think there is actually an issue in newer versions. I ithink is better to have this issue open as far as this problem exists, it will help other users of Androxyde, even if the problem behind is not found/solved.
