### ISSUE TITLE
New device support in need

### ISSUE THREAD

**Issue by hubcin** [Androxyde/Flashtool#191]
I want to flash my Xperia 5 IV, but the flash tool doesn't recognize my device. 
Is there any instructions on how to add device support for this tool? 
I will be happy to contribute to the project

**Comment by rassawyer** [comment]
I second this. It appears that the XQ-CQ54 (European Version) may be supported. I need to flash my XQ-CQ62 (American Version) to the XQ-CQ72 (SEA) so that I can (hopefully) enable WiFi calling, since our Sony Overlords saw fit to disable it 3 months after I purchased the device.
