### ISSUE TITLE
Flashtool stuck at `Reading device infomation`

### ISSUE THREAD

**Issue by cuynu** [Androxyde/Flashtool#198]
I have Sony Xperia Z3 D6603 when i tries flash with Flashtool, its just `Reading device information`
![image](https://github.com/Androxyde/Flashtool/assets/90895715/a8a7038d-4b78-4042-9204-3bc961265583)

**Comment by YT-Advanced** [comment]
Có nút Save Log to thế kia mà không biết gửi để ông tác giả fix, đúng là ngu hết cứu

**Comment by ChaoticNeutralCzech** [comment]
I just kept retrying with different Flashtool versions and 0.9.16.0 worked for my device (yuga). It might help to use Verbose log and copy that here as text.

**Comment by cuynu** [comment]
> I just kept retrying with different Flashtool versions and 0.9.16.0 worked for my device (yuga). It might help to use Verbose log and copy that here as text.

ok thanks, i changed new device

**Comment by cuynu** [comment]
> Có nút Save Log to thế kia mà không biết gửi để ông tác giả fix, đúng là ngu hết cứu

soi mói đến từng issue, quá hay. với lại kia là máy qua Teamviewer và tôi không muốn pull file qua máy chính
