### ISSUE TITLE
XperiFirm integration missing (in Linux version)?

### ISSUE THREAD

**Issue by tomty89** [Androxyde/Flashtool#20]
I just downloaded the latest FlashTool:
3150d2d45b6b8e3eb96fc59591664a81  flashtool-0.9.18.6-linux.tar.7z
and I found that there's no "Check Updates" in the "Devices" menu anymore. Neither do I see a new button on the main window. Is it something expected?

**Comment by jbbandos** [comment]
I have the same issue, both on 0.9.18.6 and 0.9.19.0. I am running Manjaro, and have mono installed.

**Comment by tomty89** [comment]
https://github.com/Androxyde/Flashtool/commit/012de8fd42dc81a7bccf6e579a69dffdf49fe379#diff-f3afc7b184c7ef97b681dfd8dc3f7884L593

http://www.xperiablog.net/2015/05/28/flashtool-now-integrates-xperifirm/

So the "Check Updates" I had been using wasn't THE xperifirm integration, and it is normal that we can no longer see it in the menu; However I don't understand why I am not seeing the "XF" icon like I do in Windows (as of 0.9.19.10).

![noxf](https://cloud.githubusercontent.com/assets/8604057/10299701/04f48234-6c20-11e5-8b37-07e2b6e7f606.png)
 
[tom@localhost FlashTool]$ ./FlashTool
Not running as root but Sony/SonyEriccson Vendor ID found on your udev rules
if Flashing didn't work well, run flashtool as root
Used java home : ./x10flasher_lib/linjre64

(Flashtool:3037): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
06/046/2015 11:46:54 - INFO  - (MainSWT.java:1041) - Stopping watchdogs and exiting ...
06/046/2015 11:46:54 - DEBUG - (ProcessBuilderWrapper.java:93) - adb: no process found
06/046/2015 11:46:54 - DEBUG - (ProcessBuilderWrapper.java:93) - adb.linux: no process found

From what I see in the code it seems that works have been done for the integration on linux and os x, and nothing obvious seems to prevent it to at least show up on the selector bar; so is it the integration just not yet ready on Linux or could it be some widget issue? (like, the selector bar somehow ended up too narrow to show the icon?)

**Comment by tomty89** [comment]
Okay I think I solved part of the mystery and found a workaround.

The problem is partly due to gtk3:
![swt_gtk](https://cloud.githubusercontent.com/assets/8604057/10301950/2f37a354-6c3a-11e5-8320-007e1083b1d4.png)

The selector bar shows as a block with slightly different color than the window background if gtk3 is used. So I made a copy of the block, filled it red, vertically moved it to just above the bar on the window of gtk2. You can see that obviously the icons are handled differently (width/margin, color/transparency). However I am not sure if this is an upstream java/swt issue with gtk3 or if it is caused by how Flashtool have that bar created (or maybe even the XF icon is a problematic png file?).

Anyway, as you can see, the workaround is setting env var "SWT_GTK3=0" to force java/swt to use gtk2. It might be a good idea to include this in the Flashtool executing script if nothing better can be done. (Then maybe I'll see if I can talk to upstream java about it)

**Comment by tomty89** [comment]
Apparently the issue lies on the "libswt-pi3-gtk-NNNN.so". If an swt build without gtk3 support is used (i.e. it provides only "libswt-pi-gtk-NNNN.so" but not "libswt-pi3-gtk-NNNN.so", like the swt provided in Arch [Extra] repo), the env var SWT_GTK3=0 will not be needed.

However, if another swt build with gtk3 (like the precompiled one provided on eclipsed.org and the FlashTool package) extracted a "libswt-pi3-gtk-NNNN.so" to $HOME/.swt, the env var will be needed again with the same jar if the .so is of the same build since it will be used otherwise.

By the way it seems that since the swt 4.6 stable build M2. Here is a comparison of FlashTool with swt 4.6M1 (libswt-pi3-gtk-4604.so) and 4.6M2 (libswt-pi3-gtk-4606.so):
![swt_gtk](https://cloud.githubusercontent.com/assets/8604057/10314812/62f91a20-6c89-11e5-83a0-12716d1757ae.png)

**Comment by alexhk90** [comment]
@tomty89 Thank you for the detailed explanation and workaround - I had this issue on Arch Linux as well. Sounds very similar to the GTK3 issues with Eclipse: https://bbs.archlinux.org/viewtopic.php?pid=1573701
