### ISSUE TITLE
Intent of packaging to Debian

### ISSUE THREAD

**Issue by rogers0** [Androxyde/Flashtool#68]
Dear @Androxyde,

I'm interested in packaging your software to Debian.

However I didn't find your license for your project. So I'm writing to ask.
I know there're a few files non-free, and not suitable for Debian, I can remove it before uploading to Debian archive. Here I just want to know what's your main license for this project.

Thank you!

Cheers,
Roger

**Comment by rogers0** [comment]
@Androxyde thanks for your prompting response!
we still need you to specify a proper license for the project, and I need to create a debian/copyright file before uploading.
Example of debian/copyright can be found here: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#examples
thanks!

**Comment by Bin4ry** [comment]
Hey Roger, we discussed this and we are not sure what to choose since we
never cared about it. Anything you would prefer?

Best Regards
Andreas

**Comment by Apteryks** [comment]
Hi! I'd like to package this as well for GNU Guix; if you don't have a preference for the choice of the license, may I recommend the GPLv3+? It's a good copyleft license that ensures the sources remain free.

**Comment by Bin4ry** [comment]
Hey,
thanks for the input. License added. :-)

BR
Andreas

Apteryks <notifications@github.com> schrieb am Fr., 29. Sep. 2017 um
03:26 Uhr:

**Comment by rogers0** [comment]
Thanks for resolving the license concern!

There's another issue when packaging for Debian.
Debian need every package to be built from source, which means I cannot simply add *any* jar file.
So I'm trying to build one by one.

I read the BUILD.md, and when I run:
$ ant -buildfile ant/setup-linux.xml binaries
there's a error which I cannot figure out:
```
main_lib:

JRE:
     [exec] tar: ../../../Flashtool/jre/linjre.tar: Cannot open: No such file or directory
     [exec] tar: Error is not recoverable: exiting now
     [exec] Result: 2
```

And I cannot find linjre.tar either in jdk/jre or in your git repo.
Could you kindly inform me how to get the jar? Thanks!

**Comment by rogers0** [comment]
Now I understand linjre.tar is JRE for linux. We just need to depends on JRE on debian. So we actually don't need this linjre.tar.
Problem solved for that.

I meet another issue: how to build all the src under src/ folder?
I guess it generates x10flasher.jar, but I don't know how to build it.

**Comment by derMart** [comment]
A debian/ubuntu package would be awesome, any progress with this?

**Comment by rogers0** [comment]
@Androxyde @Bin4ry @derMart 
Finally it's hitting Debian archive:
- https://tracker.debian.org/pkg/xperia-flashtool

I patched a bit to meet Debian requirement:
- no embedded jars, use all system java libraries
- no use git clone devices repo
- use libusb-1.0 system library

Next target is packaging devices repo.
