### ISSUE TITLE
ERROR - Caught exception in FS.readPipe() /Win10x64

### ISSUE THREAD

**Issue by GreyLeshy** [Androxyde/Flashtool#72]
Error only when running a 64-bit version, 32-bit opens without a problem. 
A couple of months ago everything was fine.

Win10x64 ver.1709 (16299.19)

[flashtool_2017-11-01_06-17-05.log](https://github.com/Androxyde/Flashtool/files/1434650/flashtool_2017-11-01_06-17-05.log)

**Comment by Androxyde** [comment]
Did you install the Windows Linux Subsystem  ?

2017-11-01 16:40 GMT+01:00 Andrey Cherepkov <notifications@github.com>:

**Comment by GreyLeshy** [comment]
Yes, installed. This problem is due to WSL?

**Comment by Androxyde** [comment]
Yes and no workaround at the moment

Le 3 nov. 2017 11:38, "Andrey Cherepkov" <notifications@github.com> a
écrit :

**Comment by GreyLeshy** [comment]
@Androxyde, Thank you!

**Comment by GreyLeshy** [comment]
@Androxyde, I found the solution! First, start the WSL and then run FlashTool64. There are no errors.
