### ISSUE TITLE
Error Unlock/Relock Xperia XZ Premium dual (G8142)

### ISSUE THREAD

**Issue by dskudilov** [Androxyde/Flashtool#80]
Error Unlock/Relock Xperia XZ Premium dual (G8142)
and flasher hangs on startup in debug mode (V 0.9.24.1)
Please help to solve the issue.
Tnx!

[stderr.log](https://github.com/Androxyde/Flashtool/files/1630378/stderr.log)
[stdout.log](https://github.com/Androxyde/Flashtool/files/1630379/stdout.log)
[flashtool_2018-01-14_08-28-38.log](https://github.com/Androxyde/Flashtool/files/1630380/flashtool_2018-01-14_08-28-38.log)

**Comment by dskudilov** [comment]
Hi, the critical error is fixed in v 0.9.24.2
but relock function is not present.

in BLU mode - Your phone bootloader cannot be officially unlocked.
but phone is already officially unlocked, I need to relock it.

**Comment by Androxyde** [comment]
@dskudilov ah I see my mistake I will provide you a fix soon :)

**Comment by dskudilov** [comment]
Reading variable value for Rooting-status
INFO  - Reply : ROOTED

**Comment by Androxyde** [comment]
@dskudilov did you unlock with Flashtool?

**Comment by dskudilov** [comment]
I did unlock by sony link -  https://developer.sonymobile.com/unlockbootloader/unlock-yourboot-loader/
The same unlock I did for my old phone Z5 Premium, then it was successfully flashed and relocked with flashtool.

**Comment by dskudilov** [comment]
Hello, is there any thoughts about an issue? Could it be possible to relock bootloader?

**Comment by Androxyde** [comment]
No it's not possible for this phone. The old method cannot be used

**Comment by dskudilov** [comment]
ah :(
